[package]
name = "shellcaster"
version = "0.8.1"
authors = ["Jeff Hughes <jeff.hughes@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
description = "A terminal-based podcast manager to subscribe to and play podcasts."
keywords = ["podcast", "terminal", "TUI", "curses"]
categories = ["multimedia::audio", "command-line-interface"]

homepage = "https://github.com/jeff-hughes/shellcaster"
repository = "https://github.com/jeff-hughes/shellcaster"
documentation = "https://github.com/jeff-hughes/shellcaster"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = "0.16.1"
rss = "1.9.0"
ureq = "1.3.0"
toml = "0.5.6"
serde = { version = "1.0.106", features = ["derive"] }
chrono = "0.4.11"
rfc822_sanitizer = "0.3.3"
lazy_static = "1.4.0"
regex = "1.3.6"
sanitize-filename = "0.2.1"
shellexpand = "2.0.0"
dirs = { package = "dirs-next", version = "1.0.1" }
textwrap = "0.12.1"

[target.'cfg(unix)'.dependencies]
rusqlite = "0.21.0"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.21.0", features = ["bundled"] }