# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Check and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt-get update
      - run: sudo apt-get install libncurses5-dev libncursesw5-dev
      - run: cargo check --verbose
      - run: cargo test --verbose
